# Generated by Django 5.1.3 on 2024-11-16 19:57

import django.db.models.deletion
import functools
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0002_alter_chatgroup_name_alter_groupmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, default=functools.partial(shortuuid.main.ShortUUID.random, *(), **{'length': 10}), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rtchat.chatgroup'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='id',
            field=models.CharField(default=functools.partial(shortuuid.main.ShortUUID.random, *(), **{'length': 18}), editable=False, max_length=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
