# Generated by Django 5.1.3 on 2024-11-19 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0005_alter_groupchatrequest_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrequest',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='requested_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
