# Generated by Django 5.1.3 on 2024-11-19 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0003_alter_groupchatrequest_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrequest',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to='rtchat.chatgroup'),
        ),
    ]
