# Generated by Django 5.1.3 on 2026-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0008_groupmessage_is_deleted_groupmessage_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
    ]
