# Generated by Django 5.1.3 on 2026-05-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
